-- =============================================================================
-- V3 — Organizations, carrier applications, client and carrier profiles
-- =============================================================================

CREATE TABLE organizations (
  id                     BIGINT       NOT NULL AUTO_INCREMENT,
  org_type               VARCHAR(20)  NOT NULL COMMENT 'FLEET, BROKER, CLIENT_COMPANY',
  legal_name             VARCHAR(160) NOT NULL,
  trade_name             VARCHAR(160) NULL,
  country_id             BIGINT       NOT NULL,
  address_line           VARCHAR(300) NULL,
  tax_number             VARCHAR(60)  NULL,
  responsible_name       VARCHAR(120) NULL,
  contact_email          VARCHAR(190) NULL,
  contact_phone          VARCHAR(24)  NULL,
  status                 VARCHAR(24)  NOT NULL DEFAULT 'PENDING_REVIEW'
                         COMMENT 'PENDING_REVIEW, CHANGES_REQUESTED, ACTIVE, SUSPENDED, DEACTIVATED, REJECTED',
  approved_by            BIGINT       NULL,
  approved_at            DATETIME(3)  NULL,
  rejection_reason_keys  JSON         NULL,
  created_at             DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at             DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at             DATETIME(3)  NULL,
  version                INT          NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY ix_org_type_status (org_type, status),
  KEY ix_org_country (country_id),
  CONSTRAINT fk_org_country     FOREIGN KEY (country_id)  REFERENCES countries (id),
  CONSTRAINT fk_org_approved_by FOREIGN KEY (approved_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE organization_members (
  id              BIGINT      NOT NULL AUTO_INCREMENT,
  organization_id BIGINT      NOT NULL,
  user_id         BIGINT      NOT NULL,
  org_role        VARCHAR(30) NOT NULL
                  COMMENT 'FLEET_OWNER, FLEET_DISPATCHER, FLEET_DRIVER, COMPANY_ADMIN, COMPANY_REQUESTER, BROKER_OWNER, BROKER_DISPATCHER',
  is_active       TINYINT(1)  NOT NULL DEFAULT 1,
  created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_org_member (organization_id, user_id),
  KEY ix_org_member_user (user_id),
  CONSTRAINT fk_om_org  FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
  CONSTRAINT fk_om_user FOREIGN KEY (user_id)         REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE carrier_applications (
  id                   BIGINT       NOT NULL AUTO_INCREMENT,
  carrier_type         VARCHAR(24)  NOT NULL COMMENT 'INDIVIDUAL_DRIVER, FLEET_COMPANY, BROKER_COMPANY',
  status               VARCHAR(24)  NOT NULL DEFAULT 'DRAFT'
                       COMMENT 'DRAFT, PENDING_REVIEW, CHANGES_REQUESTED, APPROVED, REJECTED',
  applicant_user_id    BIGINT       NULL,
  applicant_phone      VARCHAR(24)  NOT NULL,
  phone_verified       TINYINT(1)   NOT NULL DEFAULT 0,
  country_id           BIGINT       NOT NULL,
  current_step         INT          NOT NULL DEFAULT 1,
  total_steps          INT          NOT NULL DEFAULT 5,
  payload              JSON         NOT NULL COMMENT 'Auto-saved wizard state per step',
  declared_vehicle_cnt INT          NOT NULL DEFAULT 0,
  reason_keys          JSON         NULL,
  field_notes          JSON         NULL,
  duplicate_warnings   JSON         NULL,
  submitted_at         DATETIME(3)  NULL,
  reviewed_by          BIGINT       NULL,
  reviewed_at          DATETIME(3)  NULL,
  created_organization_id BIGINT    NULL,
  created_at           DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at           DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version              INT          NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY ix_application_status (status, submitted_at),
  KEY ix_application_phone (applicant_phone),
  KEY ix_application_country (country_id),
  CONSTRAINT fk_app_user     FOREIGN KEY (applicant_user_id) REFERENCES users (id),
  CONSTRAINT fk_app_country  FOREIGN KEY (country_id)        REFERENCES countries (id),
  CONSTRAINT fk_app_reviewer FOREIGN KEY (reviewed_by)       REFERENCES users (id),
  CONSTRAINT fk_app_org      FOREIGN KEY (created_organization_id) REFERENCES organizations (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE documents (
  id             BIGINT       NOT NULL AUTO_INCREMENT,
  owner_type     VARCHAR(24)  NOT NULL COMMENT 'APPLICATION, DRIVER, VEHICLE, ORGANIZATION, ORDER_LEG',
  owner_id       BIGINT       NOT NULL,
  doc_type       VARCHAR(60)  NOT NULL,
  file_url       VARCHAR(500) NOT NULL,
  file_name      VARCHAR(200) NULL,
  content_type   VARCHAR(80)  NULL,
  size_bytes     BIGINT       NULL,
  expiry_date    DATE         NULL,
  verify_status  VARCHAR(16)  NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, VERIFIED, REJECTED',
  verified_by    BIGINT       NULL,
  verified_at    DATETIME(3)  NULL,
  reason_keys    JSON         NULL,
  uploaded_by    BIGINT       NULL,
  created_at     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at     DATETIME(3)  NULL,
  PRIMARY KEY (id),
  KEY ix_document_owner (owner_type, owner_id),
  KEY ix_document_expiry (expiry_date, verify_status),
  CONSTRAINT fk_doc_verified_by FOREIGN KEY (verified_by) REFERENCES users (id),
  CONSTRAINT fk_doc_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE client_profiles (
  id                BIGINT      NOT NULL AUTO_INCREMENT,
  user_id           BIGINT      NOT NULL,
  client_type       VARCHAR(16) NOT NULL COMMENT 'INDIVIDUAL, COMPANY',
  organization_id   BIGINT      NULL,
  subscription_id   BIGINT      NULL COMMENT 'FK added in V9',
  rating_avg        DECIMAL(3,2) NULL,
  rating_count      INT         NOT NULL DEFAULT 0,
  completed_orders  INT         NOT NULL DEFAULT 0,
  credit_limit_minor BIGINT     NOT NULL DEFAULT 0,
  credit_used_minor  BIGINT     NOT NULL DEFAULT 0,
  created_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at        DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version           INT         NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_client_user (user_id),
  KEY ix_client_org (organization_id),
  CONSTRAINT fk_client_user FOREIGN KEY (user_id)         REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_client_org  FOREIGN KEY (organization_id) REFERENCES organizations (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE carrier_profiles (
  id                  BIGINT      NOT NULL AUTO_INCREMENT,
  user_id             BIGINT      NULL COMMENT 'Null for company carriers whose owner is an org member',
  carrier_type        VARCHAR(24) NOT NULL COMMENT 'INDIVIDUAL_DRIVER, FLEET_COMPANY, BROKER_COMPANY',
  organization_id     BIGINT      NULL,
  country_id          BIGINT      NOT NULL,
  status              VARCHAR(24) NOT NULL DEFAULT 'PENDING_REVIEW',
  tier_id             BIGINT      NULL,
  tier_manual_override TINYINT(1) NOT NULL DEFAULT 0,
  tier_override_until DATETIME(3) NULL,
  tier_override_reason VARCHAR(500) NULL,
  current_score       INT         NOT NULL DEFAULT 0,
  rating_avg          DECIMAL(3,2) NULL,
  rating_count        INT         NOT NULL DEFAULT 0,
  completed_orders    INT         NOT NULL DEFAULT 0,
  cancelled_orders    INT         NOT NULL DEFAULT 0,
  offers_sent         INT         NOT NULL DEFAULT 0,
  offers_accepted     INT         NOT NULL DEFAULT 0,
  violation_points    INT         NOT NULL DEFAULT 0,
  cod_held_minor      BIGINT      NOT NULL DEFAULT 0,
  payout_hold         TINYINT(1)  NOT NULL DEFAULT 0,
  approved_at         DATETIME(3) NULL,
  application_id      BIGINT      NULL,
  created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at          DATETIME(3) NULL,
  version             INT         NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_carrier_user (user_id),
  UNIQUE KEY uq_carrier_org (organization_id),
  KEY ix_carrier_status (status, carrier_type),
  KEY ix_carrier_country (country_id),
  KEY ix_carrier_tier (tier_id),
  CONSTRAINT fk_carrier_user    FOREIGN KEY (user_id)         REFERENCES users (id),
  CONSTRAINT fk_carrier_org     FOREIGN KEY (organization_id) REFERENCES organizations (id),
  CONSTRAINT fk_carrier_country FOREIGN KEY (country_id)      REFERENCES countries (id),
  CONSTRAINT fk_carrier_tier    FOREIGN KEY (tier_id)         REFERENCES carrier_tiers (id),
  CONSTRAINT fk_carrier_app     FOREIGN KEY (application_id)  REFERENCES carrier_applications (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE broker_carrier_contracts (
  id             BIGINT      NOT NULL AUTO_INCREMENT,
  broker_id      BIGINT      NOT NULL COMMENT 'carrier_profiles.id of the broker',
  carrier_id     BIGINT      NOT NULL COMMENT 'carrier_profiles.id of the contracted carrier',
  is_active      TINYINT(1)  NOT NULL DEFAULT 1,
  created_at     DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_broker_contract (broker_id, carrier_id),
  CONSTRAINT fk_bcc_broker  FOREIGN KEY (broker_id)  REFERENCES carrier_profiles (id) ON DELETE CASCADE,
  CONSTRAINT fk_bcc_carrier FOREIGN KEY (carrier_id) REFERENCES carrier_profiles (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE saved_addresses (
  id             BIGINT       NOT NULL AUTO_INCREMENT,
  user_id        BIGINT       NOT NULL,
  label          VARCHAR(60)  NOT NULL,
  address_line   VARCHAR(300) NOT NULL,
  lat            DECIMAL(10,7) NOT NULL,
  lng            DECIMAL(10,7) NOT NULL,
  country_id     BIGINT       NOT NULL,
  city           VARCHAR(120) NULL,
  contact_name   VARCHAR(120) NULL,
  contact_phone  VARCHAR(24)  NULL,
  note           VARCHAR(500) NULL,
  is_default     TINYINT(1)   NOT NULL DEFAULT 0,
  created_at     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at     DATETIME(3)  NULL,
  PRIMARY KEY (id),
  KEY ix_address_user (user_id, deleted_at),
  CONSTRAINT fk_address_user    FOREIGN KEY (user_id)    REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_address_country FOREIGN KEY (country_id) REFERENCES countries (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
